version: "3.9"

services:

  openmeetings:
    image: apache/openmeetings:min-7.2.0 
    container_name: openmeetings
    restart: always
    environment:
      - TZ="Europe/Moscow"
      - OM_KURENTO_WS_URL=ws://kurento:8888/kurento
      - OM_DB_HOST=postgresql
      - OM_DB_PORT=5432
      - OM_DB_TYPE=postgresql
      - OM_DB_USER=openmeetings
      - OM_DB_PASS=openmeetings
      - OM_DB_NAME=openmeetings
      - OM_USER=admin
      - OM_PASS=12345678
    ports:
      - 5443:5443
    volumes:
      - ./logs:/opt/openmeetings/logs
      - ./openmeetings_data:/opt/omdata
    depends_on:
      - kurento
      - postgresql
    networks:
      openmeetings-net:
        ipv4_address: 192.168.1.149
    restart: always

  postgresql:
    image: postgres:15-alpine
    container_name: postgresql
    volumes:
      - ./data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=openmeetings
      - POSTGRES_PASSWORD=openmeetings
      - POSTGRES_DB=openmeetings
    networks:
      openmeetings-net:
        ipv4_address: 192.168.1.150
    restart: always

  kurento:
    image: kurento/kurento-media-server
    container_name: kurento
    ports:
      - "8888:8888"
    networks:
      openmeetings-net:
        ipv4_address: 192.168.1.151
    restart: always

networks:
  openmeetings-net:
    name: openmeetings-net
    driver: macvlan
    driver_opts:
      parent: enp0s3
    ipam:
      config:
        - subnet: "192.168.1.0/24"
          gateway: "192.168.1.1"
